version: '3.8'

services:
  bot:
    build: .
    container_name: hrl_calc-container
    env_file:
      - ./bot/.env  # Указываем путь к .env внутри папки bot
    volumes:
      - .:/app
    restart: always